name: moment_dart
description: Multi-purpose immutable DateTime subclass. Supports multiple localizations to easily convert DateTime and Duration into human-readable format
version: 0.17.4
homepage: https://github.com/sadespresso/moment_dart
issue_tracker: https://github.com/sadespresso/moment_dart/issues

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1
